all: # nothing to build

install:
	mkdir -p $(DESTDIR)/var/www && cp -a /Users/jamesdbloom/git/grunt-debian-package/tasks/debian_package.js $(DESTDIR)/var/www/debian_package.js
	mkdir -p $(DESTDIR)/var/www && cp -a /Users/jamesdbloom/git/grunt-debian-package/tests/debian_package_test.js $(DESTDIR)/var/www/

